### ISSUE TITLE
Should requirements.txt be updated including more packages?

### ISSUE THREAD

**Issue by edx-h** [mims-harvard/UniTS#15]
Some packages used by the model are not listed in requirements.txt, for example, _gluonts, wandb, timm_. Is it possible to know how the requirements.txt is derived? I guess perhaps there are some reasons for not including those deliberately? And is it better to include them explicitly?

**Comment by gasvn** [comment]
[units_24_4_29.txt](https://github.com/mims-harvard/UniTS/files/15150888/units_24_4_29.txt)
Thank you for the reminder. Here is the conda env I am using.

**Comment by edx-h** [comment]
Thanks for your help. That works.
