### ISSUE TITLE
the meaning of prompt_num

### ISSUE THREAD

**Issue by Eunice-grow** [mims-harvard/UniTS#25]
Could you please explain the meaning of prompt_num?Do all pre trained models satisfy prompt_num=10?

**Comment by gasvn** [comment]
prompt_num refers to the number of tokens in the prompt. For simplicity, we use a uniform prompt_num for all models. But you can adjust this value based on the difficulty of your task. You can even set different prompt_num values for each individual task.

**Comment by Eunice-grow** [comment]
收到

**Comment by Zero-coder** [comment]
Thanks your splendid work,No offense！Then why it's called prompt_num since it's have no semantic meaning relationship with "forecasting" or "classification". Hope for an response.❤
