### ISSUE TITLE
When loading the model, _IncompatibleKeys appears.

### ISSUE THREAD

**Issue by hexiangdong2020** [mims-harvard/UniTS#4]
I renamed units_x128_pretrain_checkpoint.pth to pretrain_ckpt.pth. 
Then ran:
bash ./scripts/zero_shot/UniTS_forecast_new_length_unify.sh

Resulted in getting the following warnings:
_IncompatibleKeys(missing_keys=['module.prompt_tokens.ECL', 'module.prompt_tokens.ETTh1', 'module.prompt_tokens.Exchange', 'module.prompt_tokens.Traffic', 'module.prompt_tokens.Weather', 'module.mask_tokens.ECL', 'module.mask_tokens.ETTh1', 'module.mask_tokens.Exchange', 'module.mask_tokens.Traffic', 'module.mask_tokens.Weather', 'module.patch_embeddings.value_embedding.weight', 'module.position_embedding.pe', 'module.prompt2forecat.weights', 'module.prompt2forecat.bias', 'module.blocks.0.seq_att_block.norm1.weight', 'module.blocks.0.seq_att_block.norm1.bias', 'module.blocks.0.seq_att_block.attn_seq.qkv.weight', 'module.blocks.0.seq_att_block.attn_seq.proj.weight', 'module.blocks.0.seq_att_block.attn_seq.proj.bias', 'module.blocks.0.seq_att_block.ls1.gate.weight', 'module.blocks.0.seq_att_block.ls1.gate.bias', 'module.blocks.0.seq_att_block.proj.weight', 'module.blocks.0.seq_att_block.proj.bias', 'module.blocks.0.var_att_block.norm1.weight', 'module.blocks.0.var_att_block.norm1.bias', 'module.blocks.0.var_att_block.attn_var.qkv.weight', 'module.blocks.0.var_att_block.attn_var.proj.weight', 'module.blocks.0.var_att_block.attn_var.proj.bias', 'module.blocks.0.var_att_block.ls1.gate.weight', 'module.blocks.0.var_att_block.ls1.gate.bias', 'module.blocks.0.var_att_block.proj.weight', 'module.blocks.0.var_att_block.proj.bias', 'module.blocks.0.dynamic_mlp.norm2.weight', 'module.blocks.0.dynamic_mlp.norm2.bias', 'module.blocks.0.dynamic_mlp.mlp.fc1.weight', 'module.blocks.0.dynamic_mlp.mlp.fc1.bias', 'module.blocks.0.dynamic_mlp.mlp.seq_fc.weights', 'module.blocks.0.dynamic_mlp.mlp.seq_fc.bias', 'module.blocks.0.dynamic_mlp.mlp.prompt_fc.weights', 'module.blocks.0.dynamic_mlp.mlp.prompt_fc.bias', 'module.blocks.0.dynamic_mlp.mlp.fc2.weight', 'module.blocks.0.dynamic_mlp.mlp.fc2.bias', 'module.blocks.0.dynamic_mlp.ls2.gate.weight', 'module.blocks.0.dynamic_mlp.ls2.gate.bias', 'module.blocks.1.seq_att_block.norm1.weight', 'module.blocks.1.seq_att_block.norm1.bias', 'module.blocks.1.seq_att_block.attn_seq.qkv.weight', 'module.blocks.1.seq_att_block.attn_seq.proj.weight', 'module.blocks.1.seq_att_block.attn_seq.proj.bias', 'module.blocks.1.seq_att_block.ls1.gate.weight', 'module.blocks.1.seq_att_block.ls1.gate.bias', 'module.blocks.1.seq_att_block.proj.weight', 'module.blocks.1.seq_att_block.proj.bias', 'module.blocks.1.var_att_block.norm1.weight', 'module.blocks.1.var_att_block.norm1.bias', 'module.blocks.1.var_att_block.attn_var.qkv.weight', 'module.blocks.1.var_att_block.attn_var.proj.weight', 'module.blocks.1.var_att_block.attn_var.proj.bias', 'module.blocks.1.var_att_block.ls1.gate.weight', 'module.blocks.1.var_att_block.ls1.gate.bias', 'module.blocks.1.var_att_block.proj.weight', 'module.blocks.1.var_att_block.proj.bias', 'module.blocks.1.dynamic_mlp.norm2.weight', 'module.blocks.1.dynamic_mlp.norm2.bias', 'module.blocks.1.dynamic_mlp.mlp.fc1.weight', 'module.blocks.1.dynamic_mlp.mlp.fc1.bias', 'module.blocks.1.dynamic_mlp.mlp.seq_fc.weights', 'module.blocks.1.dynamic_mlp.mlp.seq_fc.bias', 'module.blocks.1.dynamic_mlp.mlp.prompt_fc.weights', 'module.blocks.1.dynamic_mlp.mlp.prompt_fc.bias', 'module.blocks.1.dynamic_mlp.mlp.fc2.weight', 'module.blocks.1.dynamic_mlp.mlp.fc2.bias', 'module.blocks.1.dynamic_mlp.ls2.gate.weight', 'module.blocks.1.dynamic_mlp.ls2.gate.bias', 'module.blocks.2.seq_att_block.norm1.weight', 'module.blocks.2.seq_att_block.norm1.bias', 'module.blocks.2.seq_att_block.attn_seq.qkv.weight', 'module.blocks.2.seq_att_block.attn_seq.proj.weight', 'module.blocks.2.seq_att_block.attn_seq.proj.bias', 'module.blocks.2.seq_att_block.ls1.gate.weight', 'module.blocks.2.seq_att_block.ls1.gate.bias', 'module.blocks.2.seq_att_block.proj.weight', 'module.blocks.2.seq_att_block.proj.bias', 'module.blocks.2.var_att_block.norm1.weight', 'module.blocks.2.var_att_block.norm1.bias', 'module.blocks.2.var_att_block.attn_var.qkv.weight', 'module.blocks.2.var_att_block.attn_var.proj.weight', 'module.blocks.2.var_att_block.attn_var.proj.bias', 'module.blocks.2.var_att_block.ls1.gate.weight', 'module.blocks.2.var_att_block.ls1.gate.bias', 'module.blocks.2.var_att_block.proj.weight', 'module.blocks.2.var_att_block.proj.bias', 'module.blocks.2.dynamic_mlp.norm2.weight', 'module.blocks.2.dynamic_mlp.norm2.bias', 'module.blocks.2.dynamic_mlp.mlp.fc1.weight', 'module.blocks.2.dynamic_mlp.mlp.fc1.bias', 'module.blocks.2.dynamic_mlp.mlp.seq_fc.weights', 'module.blocks.2.dynamic_mlp.mlp.seq_fc.bias', 'module.blocks.2.dynamic_mlp.mlp.prompt_fc.weights', 'module.blocks.2.dynamic_mlp.mlp.prompt_fc.bias', 'module.blocks.2.dynamic_mlp.mlp.fc2.weight', 'module.blocks.2.dynamic_mlp.mlp.fc2.bias', 'module.blocks.2.dynamic_mlp.ls2.gate.weight', 'module.blocks.2.dynamic_mlp.ls2.gate.bias', 'module.cls_head.proj_in.weight', 'module.cls_head.proj_in.bias', 'module.cls_head.cross_att.q.weight', 'module.cls_head.cross_att.kv.weight', 'module.cls_head.cross_att.proj.weight', 'module.cls_head.cross_att.proj.bias', 'module.cls_head.mlp.norm2.weight', 'module.cls_head.mlp.norm2.bias', 'module.cls_head.mlp.mlp.fc1.weight', 'module.cls_head.mlp.mlp.fc1.bias', 'module.cls_head.mlp.mlp.fc2.weight', 'module.cls_head.mlp.mlp.fc2.bias', 'module.cls_head.mlp.ls2.gate.weight', 'module.cls_head.mlp.ls2.gate.bias', 'module.forecast_head.proj_in.weight', 'module.forecast_head.proj_in.bias', 'module.forecast_head.mlp.fc1.weight', 'module.forecast_head.mlp.fc1.bias', 'module.forecast_head.mlp.fc2.weight', 'module.forecast_head.mlp.fc2.bias', 'module.forecast_head.proj_out.weight', 'module.forecast_head.proj_out.bias', 'module.forecast_head.pos_proj.weights', 'module.forecast_head.pos_proj.bias'], unexpected_keys=['student', 'optimizer', 'epoch', 'args', 'ibot_loss'])

Does this mean the models are incompatible?

**Comment by gasvn** [comment]
You need to change this if you want to change the ckpt name. https://github.com/mims-harvard/UniTS/blob/87911d7135e35419d98a136383a23f26045bff03/exp/exp_sup.py#L284

**Comment by hexiangdong2020** [comment]
We found that the mse of UniTS_forecast_new_length_unify is 0.847 if it is renamed to pretrain_ckpt.pth from units_x128_pretrain_checkpoint.pth, and 0.468 if it is renamed to pretrain_ checkpoint.pth and modify the sh file accordingly, the mse is 0.468, which is closer to the score in the paper. May I ask if the latter reproduction is correct?
![ckpt测试零样本](https://github.com/mims-harvard/UniTS/assets/127718414/51b2ac1d-154c-4eeb-8117-ef4c0ed37497)
![checkpoint测试零样本](https://github.com/mims-harvard/UniTS/assets/127718414/a7f0c6fc-10e3-484f-bcb9-0103487b6d09)

**Comment by gasvn** [comment]
> We found that the mse of UniTS_forecast_new_length_unify is 0.847 if it is renamed to pretrain_ckpt.pth from units_x128_pretrain_checkpoint.pth, and 0.468 if it is renamed to pretrain_ checkpoint.pth and modify the sh file accordingly, the mse is 0.468, which is closer to the score in the paper. May I ask if the latter reproduction is correct? ![ckpt测试零样本](https://private-user-images.githubusercontent.com/127718414/313537095-51b2ac1d-154c-4eeb-8117-ef4c0ed37497.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzEzMjMsIm5iZiI6MTcxMDczMTAyMywicGF0aCI6Ii8xMjc3MTg0MTQvMzEzNTM3MDk1LTUxYjJhYzFkLTE1NGMtNGVlYi04MTE3LWVmNGMwZWQzNzQ5Ny5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQwMzAzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTVhODg3MTBjYTI2ZGExNTczYmVmNjA5NTk2YWQzYTM4ZDhjNTYwZjUzODc5MGJkNWUxOGZmZTdiMTMyOWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ONQRZb9cKJBkGeEt6CRnomKw9gUBcsF0-zAqpcxDABI) ![checkpoint测试零样本](https://private-user-images.githubusercontent.com/127718414/313537105-a7f0c6fc-10e3-484f-bcb9-0103487b6d09.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzEzMjMsIm5iZiI6MTcxMDczMTAyMywicGF0aCI6Ii8xMjc3MTg0MTQvMzEzNTM3MTA1LWE3ZjBjNmZjLTEwZTMtNDg0Zi1iY2I5LTAxMDM0ODdiNmQwOS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQwMzAzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDQ1NWYxNTAzYjRlOGY2MzJkZjU2YTRiMDEzODViNjdlZjY2ZDEzZjQ4ZWRkODE3NjliYTM1NDExNWFmM2YyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R_uiLVJBY9U65aEkES8DxfoWol4Jkoj666QvULSLGN4)

I think the later one is correct. For the first one, you should be able to see the log that shows the pretrained weights are not correctly loaded.
