### ISSUE TITLE
How is the internal review going? What's the status?

### ISSUE THREAD

**Issue by ChrisCarini** [mims-harvard/UniTS#6]
I see the README.md was updated with the below on 2024-03-04 in https://github.com/mims-harvard/UniTS/commit/762fafc66c843aa1e8406425c34cbb067b6fd08b , which also removed a large number of files (already mentioned in #5)

> The code is currently undergoing an internal administrative review and is scheduled for release within this week.

Given it's been about 2 weeks, just curious what the status of the internal review is, and if there are plans to revert that commit, or update the repo with the latest information/code.

**Comment by gasvn** [comment]
The code is back online now! Thank you for your patience!
